language: java
install: cd spark-kmedoids && mvn --quiet install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -DargLine="-Xmx2G"
script: mvn clean install -Dmaven.javadoc.skip=true -Dgpg.skip=true -DargLine="-Xmx2G"

after_success:
  - mvn clean test jacoco:report coveralls:report

#env:
#  - SPARKVERSION="1.5.2"
#  - SPARKVERSION="1.6.0"
#  - SPARKVERSION="1.4.1"
#  - SPARKVERSION="1.6.2"
#after_success:
#  - cd spark-knn-graphs && mvn cobertura:cobertura coveralls:report
